### ISSUE TITLE
[Bug] EngineCore crash on RTX 5090 when using --kv-transfer-config with lmcache/vllm-openai:latest

### ISSUE THREAD

**Issue by nadongjun** [LMCache/LMCache#1646]
**Label**
Please label your issue with "bug" and any other relevant labels so that it can easily be easily categorized under [LMCache Onboarding](https://github.com/LMCache/LMCache/issues/627)

**Describe the bug**
Running lmcache/vllm-openai:latest on an RTX 5090 (SM120) with --kv-transfer-config enabled causes EngineCore to crash.
The error trace shows:
```
torch.AcceleratorError: CUDA error: no kernel image is available for execution on the device
at lmcache/v1/gpu_connector.py -> lmc_ops.multi_layer_kv_transfer
```

Disabling --kv-transfer-config resolves the issue, so the problem appears to be specific to LMCache GPU kernels for SM120.

**To Reproduce**
1.	Launch container with environment variables:
```
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
TORCH_CUDA_ARCH_LIST=12.0
TORCH_COMPILE_DISABLE=1
LMCACHE_CHUNK_SIZE=256
LMCACHE_LOCAL_CPU=True
LMCACHE_MAX_LOCAL_CPU_SIZE=5
```

2. Start command:
```
openai/gpt-oss-20b \
  --max-model-len 16000 \
  --disable-hybrid-kv-cache-manager \
  --gpu-memory-utilization 0.95 \
  --disable-log-requests \
  --tool-call-parser openai \
  --reasoning-parser openai_gptoss \
  --enable-auto-tool-choice \
  --kv-transfer-config '{"kv_connector":"LMCacheConnectorV1","kv_role":"kv_both"}'
```

3. Start command:
```
curl http://localhost:8000/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d '{"model":"openai/gpt-oss-20b","messages":[{"role":"user","content":"hello"}]}'
```

**Expected behavior**
The server should handle chat completion requests successfully with --kv-transfer-config enabled, even on RTX 5090.

**Screenshots**

**Desktop (please complete the following information):**
- OS: Ubuntu 22.04 (inside container host)
- Docker Image: lmcache/vllm-openai:latest
- CUDA: 12.9 (from nvidia-smi)

**Smartphone (please complete the following information):**

**Additional context**
- Disabling --kv-transfer-config avoids the crash, so LMCache GPU kernel path (multi_layer_kv_transfer) is the likely cause.
- [full_log.log](https://github.com/user-attachments/files/22423822/vllm_log.log)

**Comment by nadongjun** [comment]
This is now working correctly with `lmcache/vllm-openai:nightly-2025-09-21`.

**Comment by IdleIdiot** [comment]
Encountered this issue in version 0.3.7. GPU: 5070 Ti

<img width="1465" height="801" alt="Image" src="https://github.com/user-attachments/assets/92da529b-301f-4f81-96f9-4e529ca05197" />

**Comment by nadongjun** [comment]
@IdleIdiot Did you manage to resolve this issue?

**Comment by IdleIdiot** [comment]
> [@IdleIdiot](https://github.com/IdleIdiot) Did you manage to resolve this issue?

It looks good now. I fixed it by installing the latest LMCache from source, but I'm still unsure of the root cause.
