### ISSUE TITLE
[Bug]: The number of retrieved tokens is less than the expected number of tokens

### ISSUE THREAD

**Issue by tianlang-wq** [LMCache/LMCache#1690]
我部署了一个pd分离的模型服务，请求时prefill报下面错误，这是什么原因造成的？lmcache检查到mooncake-master有这个key对应的信息但是store里没有？ 每次只能重新部署mooncake才能解决。 mooncake使用的ha模式

INFO 09-25 00:42:05 [async_llm.py:270] Added request chatcmpl-2c45aa08-405b-4d28-9d72-8ad3058f6852.
[2025-09-25 00:42:05,968] LMCache INFO: Reqid: chatcmpl-2c45aa08-405b-4d28-9d72-8ad3058f6852, Total tokens 32, LMCache hit tokens: 32, need to load: 31 (vllm_v1_adapter.py:1048:lmcache.integration.vllm.vllm_v1_adapter)
INFO 09-25 00:42:05 [ray_distributed_executor.py:569] RAY_CGRAPH_get_timeout is set to 300
INFO 09-25 00:42:05 [ray_distributed_executor.py:571] VLLM_USE_RAY_COMPILED_DAG_CHANNEL_TYPE = auto
INFO 09-25 00:42:05 [ray_distributed_executor.py:573] VLLM_USE_RAY_COMPILED_DAG_OVERLAP_COMM = False
(RayWorkerWrapper pid=999) [2025-09-25 00:42:06,066] LMCache INFO: Post-initializing LMCacheEngine (cache_engine.py:177:lmcache.v1.cache_engine)
(RayWorkerWrapper pid=999) [2025-09-25 00:42:06,089] LMCache WARNING: The cache block is in the storage, but it can't be retrieved (cache_engine.py:1087:lmcache.v1.cache_engine)
(RayWorkerWrapper pid=999) [2025-09-25 00:42:06,089] LMCache INFO: Retrieved 0 out of 32 out of total 32 tokens (cache_engine.py:499:lmcache.v1.cache_engine)
(RayWorkerWrapper pid=999) [2025-09-25 00:42:06,089] LMCache ERROR: The number of retrieved tokens is less than the expected number of tokens! This should not happen! (vllm_v1_adapter.py:751:lmcache.integration.vllm.vllm_v1_adapter)
(RayWorkerWrapper pid=999) [2025-09-25 00:42:06,089] LMCache ERROR: Num retrieved tokens: 0, num expected tokens: 32 (vllm_v1_adapter.py:755:lmcache.integration.vllm.vllm_v1_adapter)
INFO 09-25 00:42:14 [loggers.py:118] Engine 000: Avg prompt throughput: 3.2 tokens/s, Avg generation throughput: 0.1 tokens/s, Running: 0 reqs, Waiting: 0 reqs, GPU KV cache usage: 0.0%, Prefix cache hit rate: 0.0%
INFO 09-25 00:42:24 [loggers.py:118] Engine 000: Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Waiting: 0 reqs, GPU KV cache usage: 0.0%, Prefix cache hit rate: 0.0%
``

按理说lmcache 检查到有但是获取失败后应该重新计算再存储吧？是这个流程吗？

**Comment by jayashreemohan29** [comment]
Any update on this thread? facing this issue consistently with Mooncake v0.3.6 + LMcache v0.3.6 + vllm v0.10.2. Kv is not being written if it is unable to retrieve it.

**Comment by xiaguan** [comment]
Could u try increase master's lease time to 5min?

```
mooncake_master --default_kv_lease_ttl=50000
```

**Comment by jayashreemohan29** [comment]
Doesn't help. This error is happening when a request is freshly made - we donot expect KV match to happen in this case. Logs for ref:

I am running mooncake server locally on a node without RDMA and have set export MC_STORE_MEMCPY=1

qE20250929 10:56:10.833086 615540 pybind_client.cpp:425] Client is not initialized
(EngineCore_DP0 pid=614629) [2025-09-29 10:56:10,833] LMCache INFO: Reqid: cmpl-ca3850aef7d14014a8401dc31763ba88-0, Total tokens 6, LMCache hit tokens: 6, need to load: 5 (vllm_v1_adapter.py:1104:lmcache.integration.vllm.vllm_v1_adapter)
(EngineCore_DP0 pid=614629) [2025-09-29 10:56:10,835] LMCache INFO: Post-initializing LMCacheEngine (cache_engine.py:191:lmcache.v1.cache_engine)
E20250929 10:56:10.835877 615540 pybind_client.cpp:425] Client is not initialized
E20250929 10:56:10.836403 617525 pybind_client.cpp:553] Client is not initialized
(EngineCore_DP0 pid=614629) [2025-09-29 10:56:10,836] LMCache WARNING: Buffer 0 is None for key vllm@meta-llama/Llama-3.1-8B-Instruct@1@0@-6da5c4c98506a6dc (mooncakestore_connector.py:366:lmcache.v1.storage_backend.connector.mooncakestore_connector)
(EngineCore_DP0 pid=614629) [2025-09-29 10:56:10,836] LMCache WARNING: The cache block is in the storage, but it can't be retrieved (cache_engine.py:1197:lmcache.v1.cache_engine)
(EngineCore_DP0 pid=614629) [2025-09-29 10:56:10,836] LMCache INFO: Retrieved 0 out of total 6 out of total 6 tokens. size: 0.0000 gb, cost 1.3421 ms, throughput: 0.0000 GB/s; (cache_engine.py:519:lmcache.v1.cache_engine)
(EngineCore_DP0 pid=614629) [2025-09-29 10:56:10,837] LMCache ERROR: The number of retrieved tokens is less than the expected number of tokens! This should not happen! (vllm_v1_adapter.py:795:lmcache.integration.vllm.vllm_v1_adapter)
(EngineCore_DP0 pid=614629) [2025-09-29 10:56:10,837] LMCache ERROR: Num retrieved tokens: 0, num expected tokens: 6 (vllm_v1_adapter.py:799:lmcache.integration.vllm.vllm_v1_adapter)

**Comment by xiaguan** [comment]
```
qE20250929 10:56:10.833086 615540 pybind_client.cpp:425] Client is not initialized
```

This is an error, meaning the Mooncake client didn't initialize successfully.

**Comment by jayashreemohan29** [comment]
Is there a reason why this could be happening? v0.3.5 of both MC and LMCache worked fine. MC store and master connection is successfully setup though. This is the log prior to this error

I20250929 10:55:32.617178 614629 transfer_engine.cpp:185] Auto-discovering topology...
I20250929 10:55:32.621214 614629 transfer_engine.cpp:200] Topology discovery complete. Found 1 HCAs.
I20250929 10:55:32.627466 614629 rdma_context.cpp:491] Find best gid index: 0 on mlx5_0/
E20250929 10:55:32.627507 614629 rdma_context.cpp:499] Failed to query GID 0 on mlx5_0/: Invalid argument [22]
E20250929 10:55:32.628151 614629 rdma_context.cpp:70] Failed to open device mlx5_0 on port  with GID 0
W20250929 10:55:32.628182 614629 rdma_transport.cpp:420] Disable device mlx5_0
E20250929 10:55:32.628197 614629 rdma_transport.cpp:426] RdmaTransport: No available RNIC
E20250929 10:55:32.628209 614629 rdma_transport.cpp:60] RdmaTransport: cannot initialize RDMA resources
E20250929 10:55:32.628221 614629 transfer_engine.cpp:234] Failed to install RDMA transport
E20250929 10:55:32.628232 614629 client.cpp:228] Failed to initialize transfer engine, rc=-1
E20250929 10:55:32.628245 614629 client.cpp:341] Failed to initialize transfer engine
E20250929 10:55:32.628932 614629 pybind_client.cpp:123] Failed to create client
(EngineCore_DP0 pid=614629) [2025-09-29 10:55:32,629] LMCache INFO: Mooncake store setup completed successfully (mooncakestore_connector.py:158:lmcache.v1.storage_backend.connector.mooncakestore_connector)
E20250929 10:55:32.629436 614629 pybind_client.cpp:660] Client is not initialized
(EngineCore_DP0 pid=614629) [2025-09-29 10:55:32,629] LMCache WARNING: Buffer registration failed: error=-600 (mooncakestore_connector.py:216:lmcache.v1.storage_backend.connector.mooncakestore_connector)
(EngineCore_DP0 pid=614629) [2025-09-29 10:55:32,629] LMCache INFO: MooncakeConnector initialized successfully. (mooncakestore_connector.py:182:lmcache.v1.storage_backend.connector.mooncakestore_connector)
(EngineCore_DP0 pid=614629) [2025-09-29 10:55:32,629] LMCache INFO: MooncakeConnector using legacy mode (mooncakestore_connector.py:195:lmcache.v1.storage_backend.connector.mooncakestore_connector)

**Comment by jayashreemohan29** [comment]
Okay figured the issue. It was on the Mooncake side. The auto topology discover logic has slightly changed, and forces use of RDMA transport even if it discovers one HCA. Setting export MC_FORCE_TCP=1 on your node if it doesn't support RDMA does the trick. Wish these env variables were listed somewhere for easy access rather than digging through code. Hope this helps. Thanks

**Comment by xiaguan** [comment]
sorry for this, it is a known bug in `0.3.6post1`.

**Comment by baoqian426** [comment]
这个问题解决了吗，我用0.3.7也还是报错，export MC_FORCE_TCP=1也没用

**Comment by xiaguan** [comment]
> 这个问题解决了吗，我用0.3.7也还是报错，export MC_FORCE_TCP=1也没用

mooncake还没发0.3.7,  export MC_MS_AUTO_DISC=0 也可以试一下，或者从源码编译。

**Comment by baoqian426** [comment]
> > 这个问题解决了吗，我用0.3.7也还是报错，export MC_FORCE_TCP=1也没用
> 
> mooncake还没发0.3.7, export MC_MS_AUTO_DISC=0 也可以试一下，或者从源码编译。

哦哦，我还以为是lmcache 0.3.6有问题，我说我用的是lmcache0.3.7，没看仔细，sorry，我再试一下

**Comment by baoqian426** [comment]
> > 这个问题解决了吗，我用0.3.7也还是报错，export MC_FORCE_TCP=1也没用
> 
> mooncake还没发0.3.7, export MC_MS_AUTO_DISC=0 也可以试一下，或者从源码编译。

不过我mooncake就是从源码编译的

**Comment by JZhou3083** [comment]
I believe there is an issue related to this: https://github.com/LMCache/LMCache/issues/1686
