### ISSUE TITLE
localdisk offload ,   LMCache hit tokens: 0

### ISSUE THREAD

**Issue by jiaozenghui** [LMCache/LMCache#1788]
**Label**
Please label your issue so that it can easily be easily categorized under [LMCache Onboarding](https://github.com/LMCache/LMCache/issues/627)

**Summary**
when id  use lmcache to offload kvcache to local disk,  LMCache hit tokens are always 0

 LMCACHE_CONFIG_FILE=/data2/jzh/p2p/lm1.yaml LMCACHE_USE_EXPERIMENTAL=True CUDA_VISIBLE_DEVICES=0,1 NCCL_DEBUG=INFO /opt/venv/bin/vllm serve /data2/DeepSeek-R1-Distill-Qwen-32B     --trust-remote-code     --tensor-parallel-size 2     --host 0.0.0.0     --gpu-memory-utilization 0.78     --port 9000     --kv-transfer-config '{"kv_connector":"LMCacheConnectorV1", "kv_role":"kv_both"}'     --max-model-len 13000     --enforce-eager     --no-enable-prefix-caching

lm1.yaml content ：
chunk_size: 256
local_cpu: true
max_local_cpu_size: 5
local_disk: "file:///data2/lmcace/gd-offload/cache"
max_local_disk_size: 150
extra_config: {'use_odirect': True}

logs:

(APIServer pid=2830) INFO:     10.121.129.6:37650 - "POST /v1/completions HTTP/1.1" 200 OK
(EngineCore_DP0 pid=3111) [2025-10-14 06:03:06,400] LMCache INFO: Reqid: cmpl-ae76e17a6e364fcc8b9d6459f5e750cd-0, Total tokens 26, LMCache hit tokens: 0, need to load: 0 (vllm_v1_adapter.py:1191:lmcache.integration.vllm.vllm_v1_adapter)

**Comment by sammshen** [comment]
Please set the `PYTHONHASHSEED=0` for deterministic hashing between workers!

**Comment by jiaozenghui** [comment]
> Please set the `PYTHONHASHSEED=0` for deterministic hashing between workers!

thank you ,it works,  and  sorry, I have an another question:   I want to use p2p sharing,   I started two LLM instances:

**lm1.yaml**

chunk_size: 256
local_cpu: true
max_local_cpu_size: 5
local_disk: "file:///data2/lmcace/gd-offload/cache"
max_local_disk_size: 150
extra_config: {'use_odirect': True}
enable_p2p: true
lookup_url: "localhost:8100"
distributed_url: "localhost:8200"

**lm2.yaml:**
chunk_size: 256
local_cpu: true
max_local_cpu_size: 5
local_disk: "file:///data2/lmcace/gd-offload/cache1"
max_local_disk_size: 150
extra_config: {'use_odirect': True}
enable_p2p: true
lookup_url: "localhost:8100"
distributed_url: "localhost:8201"

but It looks like, LLM instances  can not share kvcache  from local disk  with each other

**Comment by jiaozenghui** [comment]
> Please set the `PYTHONHASHSEED=0` for deterministic hashing between workers!

#1189   My scenario is similar to this question

**Comment by sammshen** [comment]
it looks like you set two differetn local_disk paths between the two instances

**Comment by alikhabazian** [comment]
Hi, and thanks to @sammshen — their guidance really helped me set up the lmcache server.

However, I’m running into an issue when trying to make lmcache persist the model only on disk. After shutting down and starting up again, the cache doesn’t seem to be reused (output of second run same request). Even setting `PYTHONHASHSEED=0` didn’t fix the problem.
```
Reqid: cmpl-3e23278ecacc47fcad0d4bc49a67f34b-0, Total tokens 160, LMCache hit tokens: 0, need to load: 0 (vllm_v1_adapter.py:1330:lmcache.integration.vllm.vllm_v1_adapter)
```
Here are more details about my setup and how I’m running it:
disk_config.yaml file:
```disk_config.yaml 
chunk_size: 8
local_cpu: false
max_local_cpu_size: 5.0
local_disk: "file:/myfile/disk_data"
max_local_disk_size: 5.0
```
first run
```
LMCACHE_CONFIG_FILE="disk_config.yaml" LMCACHE_USE_EXPERIMENTAL=True  PYTHONHASHSEED=0   vllm serve     Qwen/Qwen3-0.6B     --kv-transfer-config     '{"kv_connector":"LMCacheConnectorV1", "kv_role":"kv_both"}' --port 8085
```
output first run
```
--------------------------------------------------------- 
(first request)
[2025-11-25 11:18:43,180] LMCache INFO: Reqid: cmpl-867ab85aaacc48d4832a910c3234f397-0, Total tokens 160, LMCache hit tokens: 0, need to load: 0 (vllm_v1_adapter.py:1330:lmcache.integration.vllm.vllm_v1_adapter)
(EngineCore_DP0 pid=1119026) [2025-11-25 11:18:43,199] LMCache INFO: Post-initializing LMCacheEngine (cache_engine.py:179:lmcache.v1.cache_engine)
(EngineCore_DP0 pid=1119026) [2025-11-25 11:18:43,209] LMCache INFO: Storing KV cache for 160 out of 160 tokens (skip_leading_tokens=0) for request cmpl-867ab85aaacc48d4832a910c3234f397-0 (vllm_v1_adapter.py:1209:lmcache.integration.vllm.vllm_v1_adapter)
(EngineCore_DP0 pid=1119026) [2025-11-25 11:18:43,212] LMCache INFO: Stored 160 out of total 160 tokens. size: 0.0171 gb, cost 3.0726 ms, throughput: 5.5619 GB/s; offload_time: 2.5072 ms, put_time: 0.5654 ms (cache_engine.py:303:lmcache.v1.cache_engine)
(APIServer pid=1118897) INFO:     127.0.0.1:44038 - "POST /v1/completions HTTP/1.1" 200 OK
(APIServer pid=1118897) INFO 11-25 11:18:46 [loggers.py:236] Engine 000: Avg prompt throughput: 16.0 tokens/s, Avg generation throughput: 10.0 tokens/s, Running: 0 reqs, Waiting: 0 reqs, GPU KV cache usage: 0.0%, Prefix cache hit rate: 0.0%, External prefix cache hit rate: 0.0%
--------------------------------------------------------- 
(second request)
(EngineCore_DP0 pid=1119026) [2025-11-25 11:18:53,915] LMCache INFO: Reqid: cmpl-e9640ef0e8914ec29cd532e9bc0c06fd-0, Total tokens 160, LMCache hit tokens: 160, need to load: 15 (vllm_v1_adapter.py:1330:lmcache.integration.vllm.vllm_v1_adapter)
(EngineCore_DP0 pid=1119026) [2025-11-25 11:18:53,920] LMCache INFO: Retrieved 16 out of 16 required tokens (from 160 total tokens). size: 0.0017 gb, cost 1.9155 ms, throughput: 0.8922 GB/s; (cache_engine.py:531:lmcache.v1.cache_engine)
(APIServer pid=1118897) INFO:     127.0.0.1:45994 - "POST /v1/completions HTTP/1.1" 200 OK
(APIServer pid=1118897) INFO 11-25 11:18:56 [loggers.py:236] Engine 000: Avg prompt throughput: 16.0 tokens/s, Avg generation throughput: 10.0 tokens/s, Running: 0 reqs, Waiting: 0 reqs, GPU KV cache usage: 0.0%, Prefix cache hit rate: 45.0%, External prefix cache hit rate: 4.7%
``` 
and result in disk directory
```
vllm@Qwen-Qwen3-0.6B@1@0@145e2676093b022a@bfloat16.pt
vllm@Qwen-Qwen3-0.6B@1@0@149bfcee18693d7a@bfloat16.pt
vllm@Qwen-Qwen3-0.6B@1@0@16b2e6ff39cb9f90@bfloat16.pt
vllm@Qwen-Qwen3-0.6B@1@0@-1ade5be80b217942@bfloat16.pt
vllm@Qwen-Qwen3-0.6B@1@0@25334467514777c9@bfloat16.pt
vllm@Qwen-Qwen3-0.6B@1@0@-3fa41f6c7b74e0c2@bfloat16.pt
vllm@Qwen-Qwen3-0.6B@1@0@-3fb27e824994e8fa@bfloat16.pt
vllm@Qwen-Qwen3-0.6B@1@0@-43660fbb58413be1@bfloat16.pt
vllm@Qwen-Qwen3-0.6B@1@0@-45ebb1c14004da15@bfloat16.pt
vllm@Qwen-Qwen3-0.6B@1@0@4942bb81fb8b0270@bfloat16.pt
vllm@Qwen-Qwen3-0.6B@1@0@-56d2edcde7966217@bfloat16.pt
vllm@Qwen-Qwen3-0.6B@1@0@62293321abc6d83@bfloat16.pt
vllm@Qwen-Qwen3-0.6B@1@0@653b006488fdc9a6@bfloat16.pt
vllm@Qwen-Qwen3-0.6B@1@0@-6a4ff249fb77a308@bfloat16.pt
vllm@Qwen-Qwen3-0.6B@1@0@-73aece61b0d9ec24@bfloat16.pt
vllm@Qwen-Qwen3-0.6B@1@0@768200a3931803d5@bfloat16.pt
vllm@Qwen-Qwen3-0.6B@1@0@-795b2a4ab9202871@bfloat16.pt
vllm@Qwen-Qwen3-0.6B@1@0@7c65aca50108985b@bfloat16.pt
vllm@Qwen-Qwen3-0.6B@1@0@7e8ca5481dee301a@bfloat16.pt
vllm@Qwen-Qwen3-0.6B@1@0@-ec906095276dab4@bfloat16.pt
```


second run
```
LMCACHE_CONFIG_FILE="disk_config.yaml" LMCACHE_USE_EXPERIMENTAL=True  PYTHONHASHSEED=0   vllm serve     Qwen/Qwen3-0.6B     --kv-transfer-config     '{"kv_connector":"LMCacheConnectorV1", "kv_role":"kv_both"}' --port 8085
```
output second run
```
[2025-11-25 11:19:59,491] LMCache INFO: Reqid: cmpl-3e23278ecacc47fcad0d4bc49a67f34b-0, Total tokens 160, LMCache hit tokens: 0, need to load: 0 (vllm_v1_adapter.py:1330:lmcache.integration.vllm.vllm_v1_adapter)
(EngineCore_DP0 pid=1121356) [2025-11-25 11:19:59,493] LMCache INFO: Post-initializing LMCacheEngine (cache_engine.py:179:lmcache.v1.cache_engine)
(EngineCore_DP0 pid=1121356) [2025-11-25 11:19:59,501] LMCache INFO: Storing KV cache for 160 out of 160 tokens (skip_leading_tokens=0) for request cmpl-3e23278ecacc47fcad0d4bc49a67f34b-0 (vllm_v1_adapter.py:1209:lmcache.integration.vllm.vllm_v1_adapter)
(EngineCore_DP0 pid=1121356) [2025-11-25 11:19:59,505] LMCache INFO: Stored 160 out of total 160 tokens. size: 0.0171 gb, cost 3.9645 ms, throughput: 4.3108 GB/s; offload_time: 2.4663 ms, put_time: 1.4982 ms (cache_engine.py:303:lmcache.v1.cache_engine)
(APIServer pid=1121251) INFO:     127.0.0.1:44338 - "POST /v1/completions HTTP/1.1" 200 OK
(APIServer pid=1121251) INFO 11-25 11:20:07 [loggers.py:236] Engine 000: Avg prompt throughput: 14.2 tokens/s, Avg generation throughput: 8.8 tokens/s, Running: 0 reqs, Waiting: 0 reqs, GPU KV cache usage: 0.0%, Prefix cache hit rate: 0.0%, External prefix cache hit rate: 0.0%
```

**Comment by sammshen** [comment]
@alikhabazian good catch. loading the KV cache on startup for persistent storage was in LMCache v0 but wasn't migrated to v1. This is a pretty important feature. Would you have any interest in implementing this?

**Comment by alikhabazian** [comment]
> @alikhabazian good catch. loading the KV cache on startup for persistent storage was in LMCache v0 but wasn't migrated to v1. This is a pretty important feature. Would you have any interest in implementing this?

Sure! I’m interested in contributing and can work on adding KV-cache loading at startup.
