### ISSUE TITLE
WSL OOM Error When Running 14B INT4 Quantized Model on 24GB GPU with lmcache_vllm at 90% gpu-memory-utilization

### ISSUE THREAD

**Issue by chrisoutwright** [LMCache/LMCache#259]
**Describe the bug**  
Running a 14B INT4 quantized model (`Qwen/Qwen2.5-14B-Instruct-GPTQ-Int4`) using `lmcache_vllm` on WSL consistently results in out-of-memory (OOM) errors, even with 24GB of GPU memory available and the GPU memory utilization explicitly set to 90%. The error occurs during runtime, specifically while saving KV cache data or processing inputs. This seems inconsistent with the model's configuration, given that INT4 models are designed to minimize memory consumption.

**To Reproduce**  
1. Install `lmcache_vllm` and its dependencies on a WSL-based system.  
2. Use a system with a 24GB GPU.  
3. Run the following command:  
   ```bash
   lmcache_vllm serve "Qwen/Qwen2.5-14B-Instruct-GPTQ-Int4" --host 0.0.0.0 --port 5001 --gpu-memory-utilization 0.90 --max_model_len 15000 --max-num-seqs 1
   ```
4. Send a request to `/v1/chat/completions`.  
5. Observe the server crash with an OOM error.

**Expected behavior**  
The server should successfully load and execute the INT4 quantized model without running out of GPU memory, especially on a system with 24GB of VRAM and `gpu-memory-utilization` set to 90%.

**Screenshots**  
Not applicable. Full logs are provided for reference.

**Desktop (please complete the following information):**  
- **OS**: Windows Subsystem for Linux (WSL)  
- **Environment**: Miniconda environment with Python 3.12  
- **Version**:  
  - lmcache_vllm: 0.6.2.2  
  - PyTorch: 2.4.0  
  - GPU: NVIDIA GPU with 24GB memory  

**Smartphone**  
Not applicable.

**Additional context**  
- Observed warnings indicate that the system uses `pin_memory=False` due to WSL detection, which may slow down performance.  
- The error log suggests a CUDA OOM issue occurs during the KV cache saving stage:  
  ```
  RuntimeError: CUDA error: out of memory
  ```
- Adjustments like reducing `gpu_memory_utilization` or enabling eager mode (`--enforce-eager`) are impractical, as they do not align with the model's intended lightweight configuration.

**Additional Notes:**  
Steps taken to set up the WSL environment for running `lmcache_vllm`:

1. Created the working directory:
   ```bash
   cd /
   cd root
   mkdir vllm_stuff
   cd vllm_stuff/
   ```

2. Downloaded the Miniconda installer:
   ```bash
   wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
   ```

3. Updated and upgraded the package list, then successfully installed packages:
   ```bash
   sudo apt update && sudo apt upgrade -y
   sudo apt install -y python3 python3-pip python3-venv build-essential gcc libopenblas-dev git curl
   ```

4. Installed Miniconda:
   ```bash
   bash Miniconda3-latest-Linux-x86_64.sh
   ```

5. Accepted the license agreement and confirmed the installation location (`/root/miniconda3`). Restarted the shell:
   ```bash
   source ~/.bashrc
   ```

6. Created and activated a new Conda environment:
   ```bash
   conda create -n myenv python=3.12 -y
   conda activate myenv
   ```

7. Installed CUDA support:
   - Downloaded and configured the NVIDIA CUDA repository:
     ```bash
     wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin
     sudo mv cuda-ubuntu2204.pin /etc/apt/preferences.d/cuda-repository-pin-600
     wget https://developer.download.nvidia.com/compute/cuda/12.4.0/local_installers/cuda-repo-ubuntu2204-12-4-local_12.4.0-550.54.14-1_amd64.deb
     sudo dpkg -i cuda-repo-ubuntu2204-12-4-local_12.4.0-550.54.14-1_amd64.deb
     sudo cp /var/cuda-repo-ubuntu2204-12-4-local/cuda-*-keyring.gpg /usr/share/keyrings/
     sudo apt-get update
     ```

   - Exported CUDA environment variables:
     ```bash
     export CUDA_HOME=/usr/local/cuda
     export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64
     source ~/.bashrc  # Adjust to your shell
     ```

8. Installed Python packages required for `lmcache_vllm`:
   ```bash
   cd /root/vllm_stuff
   pip install lmcache lmcache_vllm
   ```

**Comment by chrisoutwright** [comment]
10k worked, but this is really a lot less than I got it working with vllm alone with about 28k

**Comment by ApostaC** [comment]
Hey @chrisoutwright , thanks for submitting issue to LMCache. Currently, LMCache uses some temporary GPU buffer when copying out the KV cache from vLLM. Therefore, it needs some extra GPU memory. 

Can you try decreasing vLLM's GPU memory utilization? Say something like 0.8 or 0.7?

In the meantime, we do have some plans to permanently solve this issue by writing some CUDA kernels (see #88 )

**Comment by huaxuan250** [comment]
Same issue with sending loads around 120K context
Running on H100 with 80GB of VRAMs, Vllm utilization is set to be 0.6
This is the peak idle Vllm utilization but the GPU OOM issue is still frequent
```
Thu Jun 19 20:52:56 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.133.20             Driver Version: 570.133.20     CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA H100 80GB HBM3          On  |   00000000:53:00.0 Off |                    0 |
| N/A   36C    P0            119W /  700W |   42677MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA H100 80GB HBM3          On  |   00000000:64:00.0 Off |                    0 |
| N/A   38C    P0            125W /  700W |   42773MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   2  NVIDIA H100 80GB HBM3          On  |   00000000:75:00.0 Off |                    0 |
| N/A   36C    P0            114W /  700W |   42773MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   3  NVIDIA H100 80GB HBM3          On  |   00000000:86:00.0 Off |                    0 |
| N/A   39C    P0            122W /  700W |   42773MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   4  NVIDIA H100 80GB HBM3          On  |   00000000:97:00.0 Off |                    0 |
| N/A   38C    P0            113W /  700W |   42773MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   5  NVIDIA H100 80GB HBM3          On  |   00000000:A8:00.0 Off |                    0 |
| N/A   36C    P0            114W /  700W |   42773MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   6  NVIDIA H100 80GB HBM3          On  |   00000000:B9:00.0 Off |                    0 |
| N/A   38C    P0            115W /  700W |   42773MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   7  NVIDIA H100 80GB HBM3          On  |   00000000:CA:00.0 Off |                    0 |
| N/A   36C    P0            118W /  700W |   42293MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A          365969      C   /opt/venv/bin/python3                 42538MiB |
|    1   N/A  N/A          365970      C   /opt/venv/bin/python3                 42634MiB |
|    2   N/A  N/A          365971      C   /opt/venv/bin/python3                 42634MiB |
|    3   N/A  N/A          365972      C   /opt/venv/bin/python3                 42634MiB |
|    4   N/A  N/A          365973      C   /opt/venv/bin/python3                 42634MiB |
|    5   N/A  N/A          365974      C   /opt/venv/bin/python3                 42634MiB |
|    6   N/A  N/A          365975      C   /opt/venv/bin/python3                 42634MiB |
|    7   N/A  N/A          365976      C   /opt/venv/bin/python3                 42154MiB |
+-----------------------------------------------------------------------------------------+
```
