### ISSUE TITLE
[Bug][MP] LMCacheMPWorkerAdapter does not retain producer-side CUDA Event after exporting ipc_handle

### ISSUE THREAD

**Issue by Alexa0625** [LMCache/LMCache#3236]
**Label**
bug, MP, vLLM integration

**Describe the bug**

When using LMCache MP mode with a standalone LMCache daemon, `LMCacheMPWorkerAdapter` sends CUDA event IPC handles to the daemon but does not appear to retain the producer-side `torch.cuda.Event` object.

In our environment, the daemon may fail when opening the event IPC handle:

```text
RuntimeError: CUDA error: invalid argument
torch.cuda.Event.from_ipc_handle(...)
```

The relevant path is:

1. vLLM `LMCacheMPConnector` creates and records an interprocess CUDA event.
2. The event is passed into `LMCacheMPWorkerAdapter`.
3. `LMCacheMPWorkerAdapter.submit_store_request()` / `submit_retrieve_request()` sends `event.ipc_handle()` to the LMCache MP daemon.
4. The adapter stores the `MessagingFuture`, but not the original `torch.cuda.Event` object.
5. If the producer-side event object is garbage-collected before the daemon opens the handle, the daemon may fail in `torch.cuda.Event.from_ipc_handle()`.

This looks like a CUDA event lifetime issue in the LMCache MP adapter.

**To Reproduce**

Our deployment topology:

- vLLM runs in Kubernetes pods.
- LMCache runs as a standalone MP daemon pod on the same node.
- vLLM connects to the daemon through `LMCacheMPConnector`.
- vLLM and the daemon use host IPC for CUDA IPC.
- The daemon receives `event.ipc_handle()` from vLLM and opens it with `torch.cuda.Event.from_ipc_handle(...)`.

vLLM is launched with:

```bash
--kv-transfer-config '{"kv_connector":"LMCacheMPConnector","kv_role":"kv_both","kv_connector_extra_config":{"lmcache.mp.host":"tcp://${NODE_IP}","lmcache.mp.port":6555}}'
```

The issue is observed during MP store/retrieve when the daemon opens the event IPC handle.

**Expected behavior**

The producer-side `torch.cuda.Event` should remain alive until the LMCache MP daemon has opened the IPC handle and the corresponding store/retrieve operation has completed.

The MP adapter should manage the lifetime of the `torch.cuda.Event` object, not only the messaging future.

**Actual behavior**

The daemon may fail with:

```text
RuntimeError: CUDA error: invalid argument
torch.cuda.Event.from_ipc_handle(...)
```

**Relevant code path**

In the vLLM connector path, an interprocess event is created and recorded:

```python
event = torch.cuda.Event(interprocess=True)
event.record()
self.worker_adapter.batched_submit_store_requests(request_ids, ops, event)
```

Then `LMCacheMPWorkerAdapter.submit_store_request()` sends only the IPC handle:

```python
future = send_lmcache_request(
    self.mq_client,
    RequestType.STORE,
    [key, self.instance_id, op.block_ids, event.ipc_handle()],
).to_cuda_future()
self.store_futures[request_id] = future
```

Similarly, `submit_retrieve_request()` sends:

```python
future = send_lmcache_request(
    self.mq_client,
    RequestType.RETRIEVE,
    [
        key,
        self.instance_id,
        op.block_ids,
        event.ipc_handle(),
        op.skip_first_n_tokens,
    ],
).to_cuda_future()
self.retrieve_futures[request_id] = (future, list(op.block_ids))
```

On the daemon side, the handle is opened with:

```python
vllm_event = torch.cuda.Event.from_ipc_handle(
    gpu_context.device, event_ipc_handle
)
```

The adapter stores `store_futures` / `retrieve_futures`, but it does not retain the original producer-side `event` object.

**Workaround tested locally**

We tested a local workaround that keeps event references inside `LMCacheMPWorkerAdapter` until the corresponding future completes.

Conceptually:

```python
self._mp_event_refs[("store", request_id)] = event
self._mp_event_refs[("retrieve", request_id)] = event
```

Then after `get_finished()` removes completed entries from `store_futures` / `retrieve_futures`, the corresponding event references are removed.

With this workaround, the `Event.from_ipc_handle(...): CUDA error: invalid argument` failure no longer occurs in our MP deployment.

**Environment**

- LMCache: dev commit `06981d6a3`
- vLLM: 0.17-based build
- Model: `Qwen/Qwen3-32B`
- Deployment: Kubernetes
- LMCache mode: MP mode, standalone daemon

**Comment by Alexa0625** [comment]
btw, there is a follow-up observation from our MP deployment.

The original issue describes the vLLM -> LMCache daemon direction, we found the reverse direction daemon -> vLLM also needs retention.

So the lifetime requirement seems bidirectional:

1. vLLM -> daemon: retain producer-side event in `LMCacheMPWorkerAdapter` until the store/retrieve future completes.
2. daemon -> vLLM: retain daemon-produced IPC events until the corresponding MP store/retrieve response has been consumed/opened by vLLM.

This fixed the `Event.from_ipc_handle(...): CUDA error: invalid argument` failure in our Kubernetes MP deployment.

Would it make sense for the upstream fix to cover both directions of CUDA IPC event lifetime?

**Comment by Alexa0625** [comment]
cc @maobaolong @DongDongJu @ApostaC @sammshen
