### ISSUE TITLE
Start GDS example on nightly build image lmcache/vllm-openai:nightly-2025-06-06 failed

### ISSUE THREAD

**Issue by maobaolong** [LMCache/LMCache#787]
**Describe the bug**

**To Reproduce**

- start container and check gds
```shell
docker run -d -it --rm --privileged --entrypoint /bin/bash --network host --name poolv1-mbl-test-3  --shm-size 512g --gpus all   -v /:/disc      mirrors.tencent.com/dop/vllm:lmcache_vllm-openai_nightly-2025-06-06 

docker exec -ti poolv1-mbl-test-3  /bin/bash

/usr/local/cuda-12.8/gds/tools/gdscheck -p
 GDS release version: 1.13.0.11
 libcufile version: 2.12
 Platform: x86_64
 ============
 ENVIRONMENT:
 ============
 =====================
 DRIVER CONFIGURATION:
 =====================
 NVMe P2PDMA        : Unsupported
 NVMe               : Unsupported
 NVMeOF             : Unsupported
 SCSI               : Unsupported
 ScaleFlux CSD      : Unsupported
 NVMesh             : Unsupported
 DDN EXAScaler      : Unsupported
 IBM Spectrum Scale : Unsupported
 NFS                : Unsupported
 BeeGFS             : Unsupported
 WekaFS             : Unsupported
 Userspace RDMA     : Unsupported
 --Mellanox PeerDirect : Enabled
 --rdma library        : Not Loaded (libcufile_rdma.so)
 --rdma devices        : Not configured
 --rdma_device_status  : Up: 0 Down: 0
 =====================
 CUFILE CONFIGURATION:
 =====================
 properties.use_pci_p2pdma : false
 properties.use_compat_mode : true
 properties.force_compat_mode : false
 properties.gds_rdma_write_support : true
 properties.use_poll_mode : false
 properties.poll_mode_max_size_kb : 4
 properties.max_batch_io_size : 128
 properties.max_batch_io_timeout_msecs : 5
 properties.max_direct_io_size_kb : 1024
 properties.max_device_cache_size_kb : 131072
 properties.max_device_pinned_mem_size_kb : 18014398509481980
 properties.posix_pool_slab_size_kb : 4 1024 16384 
 properties.posix_pool_slab_count : 128 64 64 
 properties.rdma_peer_affinity_policy : RoundRobin
 properties.rdma_dynamic_routing : 0
 fs.generic.posix_unaligned_writes : false
 fs.lustre.posix_gds_min_kb: 0
 fs.beegfs.posix_gds_min_kb: 0
 fs.weka.rdma_write_support: false
 fs.gpfs.gds_write_support: false
 fs.gpfs.gds_async_support: true
 profile.nvtx : false
 profile.cufile_stats : 0
 miscellaneous.api_check_aggressive : false
 execution.max_io_threads : 0
 execution.max_io_queue_depth : 128
 execution.parallel_io : false
 execution.min_io_threshold_size_kb : 1024
 execution.max_request_parallelism : 0
 properties.force_odirect_mode : false
 properties.prefer_iouring : false
 =========
 GPU INFO:
 =========
 GPU index 0 NVIDIA H20 bar:1 bar size (MiB):131072 supports GDS, IOMMU State: Pass-through or Enabled
 GPU index 1 NVIDIA H20 bar:1 bar size (MiB):131072 supports GDS, IOMMU State: Pass-through or Enabled
 GPU index 2 NVIDIA H20 bar:1 bar size (MiB):131072 supports GDS, IOMMU State: Pass-through or Enabled
 GPU index 3 NVIDIA H20 bar:1 bar size (MiB):131072 supports GDS, IOMMU State: Pass-through or Enabled
 GPU index 4 NVIDIA H20 bar:1 bar size (MiB):131072 supports GDS, IOMMU State: Pass-through or Enabled
 GPU index 5 NVIDIA H20 bar:1 bar size (MiB):131072 supports GDS, IOMMU State: Pass-through or Enabled
 GPU index 6 NVIDIA H20 bar:1 bar size (MiB):131072 supports GDS, IOMMU State: Pass-through or Enabled
 GPU index 7 NVIDIA H20 bar:1 bar size (MiB):131072 supports GDS, IOMMU State: Pass-through or Enabled
 ==============
 PLATFORM INFO:
 ==============
 IOMMU: Pass-through or enabled
 WARN: GDS is not guaranteed to work functionally or in a performant way with iommu=on/pt
 Nvidia Driver Info Status: Supported only on (nvidia-fs version <= 2.17.4)
 Cuda Driver Version Installed:  12020
 Platform: AG262, Arch: x86_64(Linux 5.4.241-1-tlinux4-0017.7)
 Platform verification succeeded
```

- Prepare test path
```shell
mkdir -p /mnt/gds/cache
```

- Execute the test
```shell
    # Specify LMCache V1
    export LMCACHE_USE_EXPERIMENTAL=True
    # 256 Tokens per KV Chunk
    export LMCACHE_CHUNK_SIZE=256
    # Path to store files
    export LMCACHE_GDS_PATH="/mnt/gds/cache"
    # CuFile Buffer Size in MiB
    export LMCACHE_CUFILE_BUFFER_SIZE="8192"
    # Disabling CPU RAM offload is sometimes recommended as the
    # CPU can get in the way of GPUDirect operations
    export LMCACHE_LOCAL_CPU=False

    vllm serve \
        /disc/data1/Qwen/Qwen2.5-1.5B-Instruct \
        --max-model-len 15536 \
        --kv-transfer-config \
        '{"kv_connector":"LMCacheConnectorV1", "kv_role":"kv_both"}'
```

- Error log
```
INFO 06-07 01:01:19 [__init__.py:244] Automatically detected platform cuda.
INFO 06-07 01:01:25 [api_server.py:1289] vLLM API server version 0.9.1.dev212+g7353492a4
INFO 06-07 01:01:26 [cli_args.py:309] non-default args: {'model': '/disc/data1/Qwen/Qwen2.5-1.5B-Instruct', 'max_model_len': 65536, 'kv_transfer_config': KVTransferConfig(kv_connector='LMCacheConnectorV1', engine_id='1a2afc1f-c366-46d6-a334-b82789309ca6', kv_buffer_device='cuda', kv_buffer_size=1000000000.0, kv_role='kv_both', kv_rank=None, kv_parallel_size=1, kv_ip='127.0.0.1', kv_port=14579, kv_connector_extra_config={}, kv_connector_module_path=None)}
INFO 06-07 01:01:32 [config.py:822] This model supports multiple tasks: {'classify', 'score', 'generate', 'embed', 'reward'}. Defaulting to 'generate'.
Traceback (most recent call last):
  File "/opt/venv/bin/vllm", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/vllm/entrypoints/cli/main.py", line 59, in main
    args.dispatch_function(args)
  File "/opt/venv/lib/python3.12/site-packages/vllm/entrypoints/cli/serve.py", line 58, in cmd
    uvloop.run(run_server(args))
  File "/opt/venv/lib/python3.12/site-packages/uvloop/__init__.py", line 109, in run
    return __asyncio.run(
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/opt/venv/lib/python3.12/site-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
           ^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 1325, in run_server
    await run_server_worker(listen_address, sock, args, **uvicorn_kwargs)
  File "/opt/venv/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 1345, in run_server_worker
    async with build_async_engine_client(args, client_config) as engine_client:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 157, in build_async_engine_client
    async with build_async_engine_client_from_engine_args(
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 179, in build_async_engine_client_from_engine_args
    vllm_config = engine_args.create_engine_config(usage_context=usage_context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/vllm/engine/arg_utils.py", line 1018, in create_engine_config
    model_config = self.create_model_config()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/vllm/engine/arg_utils.py", line 910, in create_model_config
    return ModelConfig(
           ^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/pydantic/_internal/_dataclasses.py", line 120, in __init__
    s.__pydantic_validator__.validate_python(ArgsKwargs(args, kwargs), self_instance=s)
pydantic_core._pydantic_core.ValidationError: 1 validation error for ModelConfig
  Value error, User-specified max_model_len (65536) is greater than the derived max_model_len (max_position_embeddings=32768 or model_max_length=None in model's config.json). This may lead to incorrect model outputs or CUDA errors. To allow overriding this maximum, set the env var VLLM_ALLOW_LONG_MAX_MODEL_LEN=1 [type=value_error, input_value=ArgsKwargs((), {'model': ..., 'model_impl': 'auto'}), input_type=ArgsKwargs]
    For further information visit https://errors.pydantic.dev/2.11/v/value_error
(venv) root@TENCENT64:/disc/data1/baoloongmao/gds# vim gds.sh 
(venv) root@TENCENT64:/disc/data1/baoloongmao/gds# sh gds.sh 
INFO 06-07 01:02:46 [__init__.py:244] Automatically detected platform cuda.
INFO 06-07 01:02:50 [api_server.py:1289] vLLM API server version 0.9.1.dev212+g7353492a4
INFO 06-07 01:02:50 [cli_args.py:309] non-default args: {'model': '/disc/data1/Qwen/Qwen2.5-1.5B-Instruct', 'max_model_len': 15536, 'kv_transfer_config': KVTransferConfig(kv_connector='LMCacheConnectorV1', engine_id='bc8b80dc-50d0-41ea-9af8-e2c506603bf6', kv_buffer_device='cuda', kv_buffer_size=1000000000.0, kv_role='kv_both', kv_rank=None, kv_parallel_size=1, kv_ip='127.0.0.1', kv_port=14579, kv_connector_extra_config={}, kv_connector_module_path=None)}
INFO 06-07 01:02:56 [config.py:822] This model supports multiple tasks: {'reward', 'generate', 'score', 'classify', 'embed'}. Defaulting to 'generate'.
INFO 06-07 01:02:56 [config.py:2182] Chunked prefill is enabled with max_num_batched_tokens=8192.
WARNING 06-07 01:02:57 [env_override.py:17] NCCL_CUMEM_ENABLE is set to 0, skipping override. This may increase memory overhead with cudagraph+allreduce: https://github.com/NVIDIA/nccl/issues/1234
INFO 06-07 01:02:59 [__init__.py:244] Automatically detected platform cuda.
INFO 06-07 01:03:02 [core.py:455] Waiting for init message from front-end.
INFO 06-07 01:03:02 [core.py:70] Initializing a V1 LLM engine (v0.9.1.dev212+g7353492a4) with config: model='/disc/data1/Qwen/Qwen2.5-1.5B-Instruct', speculative_config=None, tokenizer='/disc/data1/Qwen/Qwen2.5-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=15536, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=/disc/data1/Qwen/Qwen2.5-1.5B-Instruct, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":["none"],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"max_capture_size":512,"local_cache_dir":null}
WARNING 06-07 01:03:03 [utils.py:2723] Methods determine_num_available_blocks,device_config,get_cache_block_size_bytes,initialize_cache not implemented in <vllm.v1.worker.gpu_worker.Worker object at 0x7ff464d479b0>
INFO 06-07 01:03:04 [parallel_state.py:1065] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
WARNING 06-07 01:03:04 [rocm.py:28] Failed to import from amdsmi with ModuleNotFoundError("No module named 'amdsmi'")
WARNING 06-07 01:03:04 [rocm.py:39] Failed to import from vllm._rocm_C with ModuleNotFoundError("No module named 'vllm._rocm_C'")
INFO 06-07 01:03:05 [factory.py:74] Creating v1 connector with name: LMCacheConnectorV1 and engine_id: bc8b80dc-50d0-41ea-9af8-e2c506603bf6
WARNING 06-07 01:03:05 [base.py:71] Initializing KVConnectorBase_V1. This API is experimental and subject to change in the future as we iterate the design.
[2025-06-07 01:03:05,595] LMCache WARNING: No LMCache configuration file is set. Trying to read configurations from the environment variables. (utils.py:53:lmcache.integration.vllm.utils)
[2025-06-07 01:03:05,595] LMCache WARNING: You can set the configuration file through the environment variable: LMCACHE_CONFIG_FILE (utils.py:57:lmcache.integration.vllm.utils)
[2025-06-07 01:03:05,595] LMCache INFO: LMCache Configuration: {'chunk_size': 256, 'cufile_buffer_size': '8192', 'local_cpu': False, 'max_local_cpu_size': '5.0 GB', 'local_disk': None, 'max_local_disk_size': '0.0 GB', 'remote_url': None, 'remote_serde': None, 'save_decode_cache': False, 'enable_blending': False, 'blend_recompute_ratio': 0.15, 'blend_min_tokens': 256, 'enable_p2p': False, 'lookup_url': None, 'distributed_url': None, 'error_handling': False, 'enable_controller': False, 'lmcache_instance_id': 'lmcache_default_instance', 'enable_nixl': False, 'nixl_role': None, 'nixl_receiver_host': None, 'nixl_receiver_port': 0, 'nixl_buffer_size': 0, 'nixl_buffer_device': None, 'nixl_enable_gc': False, 'weka_path': None, 'gds_path': '/mnt/gds/cache', 'extra_config': None} (config.py:634:lmcache.v1.config)
[2025-06-07 01:03:05,596] LMCache INFO: Creating LMCacheEngine instance vllm-instance (cache_engine.py:784:lmcache.v1.cache_engine)
ERROR 06-07 01:03:05 [core.py:515] EngineCore failed to start.
ERROR 06-07 01:03:05 [core.py:515] Traceback (most recent call last):
ERROR 06-07 01:03:05 [core.py:515]   File "/opt/venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 506, in run_engine_core
ERROR 06-07 01:03:05 [core.py:515]     engine_core = EngineCoreProc(*args, **kwargs)
ERROR 06-07 01:03:05 [core.py:515]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-07 01:03:05 [core.py:515]   File "/opt/venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 390, in __init__
ERROR 06-07 01:03:05 [core.py:515]     super().__init__(vllm_config, executor_class, log_stats,
ERROR 06-07 01:03:05 [core.py:515]   File "/opt/venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 76, in __init__
ERROR 06-07 01:03:05 [core.py:515]     self.model_executor = executor_class(vllm_config)
ERROR 06-07 01:03:05 [core.py:515]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-07 01:03:05 [core.py:515]   File "/opt/venv/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 53, in __init__
ERROR 06-07 01:03:05 [core.py:515]     self._init_executor()
ERROR 06-07 01:03:05 [core.py:515]   File "/opt/venv/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 47, in _init_executor
ERROR 06-07 01:03:05 [core.py:515]     self.collective_rpc("init_device")
ERROR 06-07 01:03:05 [core.py:515]   File "/opt/venv/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 57, in collective_rpc
ERROR 06-07 01:03:05 [core.py:515]     answer = run_method(self.driver_worker, method, args, kwargs)
ERROR 06-07 01:03:05 [core.py:515]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-07 01:03:05 [core.py:515]   File "/opt/venv/lib/python3.12/site-packages/vllm/utils.py", line 2657, in run_method
ERROR 06-07 01:03:05 [core.py:515]     return func(*args, **kwargs)
ERROR 06-07 01:03:05 [core.py:515]            ^^^^^^^^^^^^^^^^^^^^^
ERROR 06-07 01:03:05 [core.py:515]   File "/opt/venv/lib/python3.12/site-packages/vllm/worker/worker_base.py", line 606, in init_device
ERROR 06-07 01:03:05 [core.py:515]     self.worker.init_device()  # type: ignore
ERROR 06-07 01:03:05 [core.py:515]     ^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-07 01:03:05 [core.py:515]   File "/opt/venv/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 138, in init_device
ERROR 06-07 01:03:05 [core.py:515]     init_worker_distributed_environment(self.vllm_config, self.rank,
ERROR 06-07 01:03:05 [core.py:515]   File "/opt/venv/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 357, in init_worker_distributed_environment
ERROR 06-07 01:03:05 [core.py:515]     ensure_kv_transfer_initialized(vllm_config)
ERROR 06-07 01:03:05 [core.py:515]   File "/opt/venv/lib/python3.12/site-packages/vllm/distributed/kv_transfer/kv_transfer_state.py", line 64, in ensure_kv_transfer_initialized
ERROR 06-07 01:03:05 [core.py:515]     _KV_CONNECTOR_AGENT = KVConnectorFactory.create_connector_v1(
ERROR 06-07 01:03:05 [core.py:515]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-07 01:03:05 [core.py:515]   File "/opt/venv/lib/python3.12/site-packages/vllm/distributed/kv_transfer/kv_connector/factory.py", line 84, in create_connector_v1
ERROR 06-07 01:03:05 [core.py:515]     return connector_cls(config, role)
ERROR 06-07 01:03:05 [core.py:515]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-07 01:03:05 [core.py:515]   File "/opt/venv/lib/python3.12/site-packages/vllm/distributed/kv_transfer/kv_connector/v1/lmcache_connector.py", line 27, in __init__
ERROR 06-07 01:03:05 [core.py:515]     self._lmcache_engine = LMCacheConnectorV1Impl(vllm_config, role, self)
ERROR 06-07 01:03:05 [core.py:515]                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-07 01:03:05 [core.py:515]   File "/opt/venv/lib/python3.12/site-packages/lmcache/integration/vllm/vllm_v1_adapter.py", line 367, in __init__
ERROR 06-07 01:03:05 [core.py:515]     self.lmcache_engine = init_lmcache_engine(
ERROR 06-07 01:03:05 [core.py:515]                           ^^^^^^^^^^^^^^^^^^^^
ERROR 06-07 01:03:05 [core.py:515]   File "/opt/venv/lib/python3.12/site-packages/lmcache/integration/vllm/vllm_adapter.py", line 218, in init_lmcache_engine
ERROR 06-07 01:03:05 [core.py:515]     engine = LMCacheEngineBuilder.get_or_create(
ERROR 06-07 01:03:05 [core.py:515]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-07 01:03:05 [core.py:515]   File "/opt/venv/lib/python3.12/site-packages/lmcache/v1/cache_engine.py", line 786, in get_or_create
ERROR 06-07 01:03:05 [core.py:515]     memory_allocator = cls._Create_memory_allocator(config, metadata)
ERROR 06-07 01:03:05 [core.py:515]                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-07 01:03:05 [core.py:515]   File "/opt/venv/lib/python3.12/site-packages/lmcache/v1/cache_engine.py", line 756, in _Create_memory_allocator
ERROR 06-07 01:03:05 [core.py:515]     return CuFileMemoryAllocator(config.cufile_buffer_size * 1024**2)
ERROR 06-07 01:03:05 [core.py:515]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-07 01:03:05 [core.py:515]   File "/opt/venv/lib/python3.12/site-packages/lmcache/v1/memory_management.py", line 1000, in __init__
ERROR 06-07 01:03:05 [core.py:515]     super().__init__(size, device, align_bytes=4096)
ERROR 06-07 01:03:05 [core.py:515]   File "/opt/venv/lib/python3.12/site-packages/lmcache/v1/memory_management.py", line 873, in __init__
ERROR 06-07 01:03:05 [core.py:515]     self.tensor = torch.empty(size, dtype=torch.uint8, device=device)
ERROR 06-07 01:03:05 [core.py:515]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-07 01:03:05 [core.py:515] TypeError: empty() received an invalid combination of arguments - got (str, device=str, dtype=torch.dtype), but expected one of:
ERROR 06-07 01:03:05 [core.py:515]  * (tuple of ints size, *, tuple of names names, torch.memory_format memory_format = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
ERROR 06-07 01:03:05 [core.py:515]  * (tuple of ints size, *, torch.memory_format memory_format = None, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
ERROR 06-07 01:03:05 [core.py:515] 
Process EngineCore_0:
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 519, in run_engine_core
    raise e
  File "/opt/venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 506, in run_engine_core
    engine_core = EngineCoreProc(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 390, in __init__
    super().__init__(vllm_config, executor_class, log_stats,
  File "/opt/venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 76, in __init__
    self.model_executor = executor_class(vllm_config)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 53, in __init__
    self._init_executor()
  File "/opt/venv/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 47, in _init_executor
    self.collective_rpc("init_device")
  File "/opt/venv/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 57, in collective_rpc
    answer = run_method(self.driver_worker, method, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/vllm/utils.py", line 2657, in run_method
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/vllm/worker/worker_base.py", line 606, in init_device
    self.worker.init_device()  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 138, in init_device
    init_worker_distributed_environment(self.vllm_config, self.rank,
  File "/opt/venv/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 357, in init_worker_distributed_environment
    ensure_kv_transfer_initialized(vllm_config)
  File "/opt/venv/lib/python3.12/site-packages/vllm/distributed/kv_transfer/kv_transfer_state.py", line 64, in ensure_kv_transfer_initialized
    _KV_CONNECTOR_AGENT = KVConnectorFactory.create_connector_v1(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/vllm/distributed/kv_transfer/kv_connector/factory.py", line 84, in create_connector_v1
    return connector_cls(config, role)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/vllm/distributed/kv_transfer/kv_connector/v1/lmcache_connector.py", line 27, in __init__
    self._lmcache_engine = LMCacheConnectorV1Impl(vllm_config, role, self)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/lmcache/integration/vllm/vllm_v1_adapter.py", line 367, in __init__
    self.lmcache_engine = init_lmcache_engine(
                          ^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/lmcache/integration/vllm/vllm_adapter.py", line 218, in init_lmcache_engine
    engine = LMCacheEngineBuilder.get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/lmcache/v1/cache_engine.py", line 786, in get_or_create
    memory_allocator = cls._Create_memory_allocator(config, metadata)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/lmcache/v1/cache_engine.py", line 756, in _Create_memory_allocator
    return CuFileMemoryAllocator(config.cufile_buffer_size * 1024**2)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/lmcache/v1/memory_management.py", line 1000, in __init__
    super().__init__(size, device, align_bytes=4096)
  File "/opt/venv/lib/python3.12/site-packages/lmcache/v1/memory_management.py", line 873, in __init__
    self.tensor = torch.empty(size, dtype=torch.uint8, device=device)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: empty() received an invalid combination of arguments - got (str, device=str, dtype=torch.dtype), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.memory_format memory_format = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
 * (tuple of ints size, *, torch.memory_format memory_format = None, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)

Exception ignored in: <function CuFileMemoryAllocator.__del__ at 0x7ff4b801d9e0>
Traceback (most recent call last):
  File "/opt/venv/lib/python3.12/site-packages/lmcache/v1/memory_management.py", line 1005, in __del__
    self.cuFileBufDeregister(ctypes.c_void_p(self.base_pointer))
                                             ^^^^^^^^^^^^^^^^^
AttributeError: 'CuFileMemoryAllocator' object has no attribute 'base_pointer'
[rank0]:[W607 01:03:06.415296093 ProcessGroupNCCL.cpp:1476] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
Traceback (most recent call last):
  File "/opt/venv/bin/vllm", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/vllm/entrypoints/cli/main.py", line 59, in main
    args.dispatch_function(args)
  File "/opt/venv/lib/python3.12/site-packages/vllm/entrypoints/cli/serve.py", line 58, in cmd
    uvloop.run(run_server(args))
  File "/opt/venv/lib/python3.12/site-packages/uvloop/__init__.py", line 109, in run
    return __asyncio.run(
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/opt/venv/lib/python3.12/site-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
           ^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 1325, in run_server
    await run_server_worker(listen_address, sock, args, **uvicorn_kwargs)
  File "/opt/venv/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 1345, in run_server_worker
    async with build_async_engine_client(args, client_config) as engine_client:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 157, in build_async_engine_client
    async with build_async_engine_client_from_engine_args(
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 193, in build_async_engine_client_from_engine_args
    async_llm = AsyncLLM.from_vllm_config(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/vllm/v1/engine/async_llm.py", line 162, in from_vllm_config
    return cls(
           ^^^^
  File "/opt/venv/lib/python3.12/site-packages/vllm/v1/engine/async_llm.py", line 124, in __init__
    self.engine_core = EngineCoreClient.make_async_mp_client(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/vllm/v1/engine/core_client.py", line 93, in make_async_mp_client
    return AsyncMPClient(vllm_config, executor_class, log_stats,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/vllm/v1/engine/core_client.py", line 716, in __init__
    super().__init__(
  File "/opt/venv/lib/python3.12/site-packages/vllm/v1/engine/core_client.py", line 422, in __init__
    self._init_engines_direct(vllm_config, local_only,
  File "/opt/venv/lib/python3.12/site-packages/vllm/v1/engine/core_client.py", line 491, in _init_engines_direct
    self._wait_for_engine_startup(handshake_socket, input_address,
  File "/opt/venv/lib/python3.12/site-packages/vllm/v1/engine/core_client.py", line 511, in _wait_for_engine_startup
    wait_for_engine_startup(
  File "/opt/venv/lib/python3.12/site-packages/vllm/v1/utils.py", line 494, in wait_for_engine_startup
    raise RuntimeError("Engine core initialization failed. "
RuntimeError: Engine core initialization failed. See root cause above. Failed core proc(s): {}
```

**Expected behavior**

Run gds example successfully.

**Comment by maobaolong** [comment]
@da-x Would you like to help to take a look at this issue? Thanks a lot!

**Comment by da-x** [comment]
The type error indicates that `torch.empty` receives a string as the first parameter due to a bug in the loading of configuration from environment. See the related PR #793 that fixes it.
